services:
  web:
    image: masoomwahid/afghangallery
    volumes:
      - ./medias:/app/medias # Bind mount for file storage
      - ./sqlite.db:/app/db.sqlite3 # Bind mount for SQLite database
    ports:
      - "3020:3020"
    command: ./start.sh
    environment:
      - SECRET_KEY=${SECRET_KEY}
volumes:
  medias:
