version: "3.8"

services:
  web:
    image: masoomwahid/afghangallery
    volumes:
      - .:/app # Bind mount your Django project folder
      - media:/app/medias # Bind mount for file storage
      - sqlite_data:/app/db # Volume for SQLite database
    ports:
      - "3020:3020"
    command: python manage.py runserver 0.0.0.0:3020

volumes:
  media:
  sqlite_data:
