services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:3020 AfghanGallery.wsgi
    volumes:
      - .:/app # Bind mount your Django project folder
      - media:/app/media # Bind mount for file storage
    ports:
      - "3020:3020"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASS=${DB_PASS}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DB_PORT}
    networks:
      - webnet

volumes:
  postgres_data:
  media:

networks:
  webnet:
