# Generated by Django 5.1 on 2024-08-19 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('num_of_ads', models.SmallIntegerField()),
                ('approval', models.CharField(blank=True, max_length=60, null=True)),
                ('vitrine', models.DurationField(db_index=True)),
                ('effective_date', models.DurationField(db_index=True)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_of_products', models.PositiveIntegerField(db_index=True, default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.packages')),
            ],
        ),
    ]
