# Generated by Django 5.1 on 2024-08-15 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('price_per_area', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('on_sale', 'On Sale'), ('rental', 'Rental')], max_length=40)),
                ('swap', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('sewage', models.BooleanField(default=False)),
                ('drilling_and_well', models.BooleanField(default=False)),
                ('road_opened', models.BooleanField(default=False)),
                ('heater', models.BooleanField(default=False)),
                ('loan_compliance', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentplan')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.realestatetype')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='real_estate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.realestate')),
            ],
        ),
    ]
