# Generated by Django 5.1 on 2024-09-21 09:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Kabul', 'Kabul'), ('Kandahar', 'Kandahar'), ('Herat', 'Herat'), ('Mazar-i-Sharif', 'Mazar-i-Sharif'), ('Kunduz', 'Kunduz'), ('Jalalabad', 'Jalalabad'), ('Ghazni', 'Ghazni'), ('Balkh', 'Balkh'), ('Faryab', 'Faryab'), ('Samangan', 'Samangan'), ('Sar-e Pol', 'Sar-e Pol'), ('Takhar', 'Takhar'), ('Baghlan', 'Baghlan'), ('Parwan', 'Parwan'), ('Kapisa', 'Kapisa'), ('Panjshir', 'Panjshir'), ('Wardak', 'Wardak'), ('Logar', 'Logar'), ('Paktia', 'Paktia'), ('Paktika', 'Paktika'), ('Khost', 'Khost'), ('Nangarhar', 'Nangarhar'), ('Laghman', 'Laghman'), ('Nuristan', 'Nuristan'), ('Badakhshan', 'Badakhshan'), ('Takhār', 'Takhār'), ('Badghis', 'Badghis'), ('Fāryāb', 'Fāryāb'), ('Ghōr', 'Ghōr'), ('Daykundi', 'Daykundi'), ('Uruzgan', 'Uruzgan'), ('Zabul', 'Zabul'), ('Helmand', 'Helmand'), ('Nimroz', 'Nimroz')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Benz', 'Benz'), ('BMW', 'BMW'), ('Chevorlet', 'Chevorlet'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Daihatsu', 'Daihatsu'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Geely', 'Geely'), ('Great Wall', 'Great Wall'), ('BYD', 'BYD'), ('Changan', 'Changan'), ('BAIC', 'BAIC'), ('Foton', 'Foton'), ('JAC', 'JAC')], max_length=150)),
                ('series', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('rental', 'Rental'), ('on_sale', 'On Sale')], max_length=20)),
                ('category', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Minivan', 'Minivan'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Roadster', 'Roadster'), ('Sports Car', 'Sports Car'), ('Luxury Car', 'Luxury Car'), ('Electric Vehicle', 'Electric Vehicle'), ('Hybrid Vehicle', 'Hybrid Vehicle'), ('MPV', 'MPV'), ('Crossover', 'Crossover'), ('Pickup Truck', 'Pickup Truck')], max_length=80)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.SmallIntegerField()),
                ('gear', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=20)),
                ('km', models.IntegerField()),
                ('engine_type', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=50)),
                ('warranty', models.BooleanField(default=False)),
                ('swap', models.BooleanField(default=False)),
                ('fuel', models.CharField(choices=[('lpg', 'Lpg'), ('petrol', 'Petrol'), ('diesel', 'Diesel')], default='petrol', max_length=120)),
                ('direction', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='left', max_length=120)),
                ('plate_no', models.IntegerField(unique=True)),
                ('plate_model', models.SmallIntegerField(db_index=True)),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_plan_activation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentplan')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='vehicle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
