# Generated by Django 5.1 on 2024-10-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='series',
        ),
    ]
