
CITY_CHOICES = [
    ('Kabul', 'Kabul'),
    ('Kandahar', 'Kandahar'),
    ('Herat', 'Herat'),
    ('Mazar-i-Sharif', 'Mazar-i-Sharif'),
    ('Kunduz', 'Kunduz'),
    ('Jalalabad', 'Jalalabad'),
    ('Ghazni', 'Ghazni'),
    ('Balkh', 'Balkh'),
    ('Faryab', 'Faryab'),
    ('Samangan', 'Samangan'),
    ('Sar-e Pol', 'Sar-e Pol'),
    ('Takhar', 'Takhar'),
    ('Baghlan', 'Baghlan'),
    ('Parwan', 'Parwan'),
    ('Kapisa', 'Kapisa'),
    ('Panjshir', 'Panjshir'),
    ('Wardak', 'Wardak'),
    ('Logar', 'Logar'),
    ('Paktia', 'Paktia'),
    ('Paktika', 'Paktika'),
    ('Khost', 'Khost'),
    ('Nangarhar', 'Nangarhar'),
    ('Laghman', 'Laghman'),
    ('Nuristan', 'Nuristan'),
    ('Badakhshan', 'Badakhshan'),
    ('Takhār', 'Takhār'),
    ('Badghis', 'Badghis'),
    ('Fāryāb', 'Fāryāb'),
    ('Ghōr', 'Ghōr'),
    ('Daykundi', 'Daykundi'),
    ('Uruzgan', 'Uruzgan'),
    ('Zabul', 'Zabul'),
    ('Helmand', 'Helmand'),
    ('Nimroz', 'Nimroz'),
]
