name: Build On Changes To Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t masoomwahid/afghangallery:latest .
          docker push masoomwahid/afghangallery:latest

      - name: reload the server in vps
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/masoom/afghangallery
            docker compose down
            docker compose pull
            docker compose up -d
